/**
 * ZIP Packager for Custom Skills
 *
 * Takes a generated skill and creates a downloadable ZIP package
 * with the standard skill file structure.
 */

import JSZip from "jszip";
import type { GeneratedSkill } from "./skill-generator";

export type PackagedSkill = {
  zip: Buffer;
  slug: string;
  files: string[];
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function getFileExtensions(skillName: string, tags: string[]): {
  codeExt: string;
  configExt: string;
} {
  const tagStr = tags.join(" ").toLowerCase();

  if (tagStr.includes("python")) return { codeExt: ".py", configExt: ".yml" };
  if (tagStr.includes("javascript") || tagStr.includes("typescript") || tagStr.includes("node"))
    return { codeExt: ".js", configExt: ".json" };
  if (tagStr.includes("rust")) return { codeExt: ".rs", configExt: ".toml" };
  if (tagStr.includes("go") || tagStr.includes("golang"))
    return { codeExt: ".go", configExt: ".yaml" };
  if (tagStr.includes("shell") || tagStr.includes("bash") || tagStr.includes("cli"))
    return { codeExt: ".sh", configExt: ".yaml" };
  if (tagStr.includes("java")) return { codeExt: ".java", configExt: ".xml" };
  if (tagStr.includes("c++") || tagStr.includes("c#"))
    return { codeExt: ".cpp", configExt: ".json" };
  if (tagStr.includes("docker") || tagStr.includes("container"))
    return { codeExt: ".sh", configExt: ".yml" };
  if (tagStr.includes("sql") || tagStr.includes("database"))
    return { codeExt: ".sql", configExt: ".json" };
  if (tagStr.includes("api") || tagStr.includes("rest") || tagStr.includes("http"))
    return { codeExt: ".js", configExt: ".json" };
  if (tagStr.includes("ml") || tagStr.includes("machine learning") || tagStr.includes("ai"))
    return { codeExt: ".py", configExt: ".yml" };
  if (tagStr.includes("data") || tagStr.includes("analytics") || tagStr.includes("visualization"))
    return { codeExt: ".py", configExt: ".json" };

  return { codeExt: ".py", configExt: ".yml" };
}

function generateMetadataYaml(skill: GeneratedSkill & { slug: string }): string {
  return `name: "${skill.name}"
category: ${skill.category}
description: "${skill.description.replace(/"/g, '\\"')}"
tags: [${skill.tags.map((t) => `"${t}"`).join(", ")}]
whenToUse: "${skill.whenToUse.replace(/"/g, '\\"')}"
source: generated
url: ""
generatedFrom: [${skill.generatedFrom.map((s) => `"${s}"`).join(", ")}]
prerequisites: [${(skill.prerequisites || []).map((s) => `"${s}"`).join(", ")}]
difficulty: ${skill.difficulty || "intermediate"}
estimatedTime: ${skill.estimatedTime || "1 hour"}
version: 1.0.0
createdAt: "${new Date().toISOString().split("T")[0]}"
`;
}

function generateReadme(skill: GeneratedSkill): string {
  const tutorialLines = skill.tutorial.split("\n");
  const steps = tutorialLines
    .filter((l) => l.startsWith("## ") || l.startsWith("### "))
    .slice(0, 5)
    .map((l) => l.replace(/^#{1,3}\s*/, ""))
    .join("\n- ");

  return `# ${skill.name}

${skill.description}

## 🎯 When to Use

${skill.whenToUse}

## 📋 Prerequisites

${(skill.prerequisites || []).map((p) => `- ${p}`).join("\n") || "No prerequisites required."}

## 📚 What You Will Learn

${(skill.whatYouWillLearn || []).map((w) => `- ${w}`).join("\n")}

## 📖 Quick Overview

${steps ? `- ${steps}` : "See TUTORIAL.md for the full guide."}

${skill.tutorial ? `## 🚀 Quick Tutorial\n\n${skill.tutorial.slice(0, 800)}${skill.tutorial.length > 800 ? "\n\n_...see TUTORIAL.md for the full tutorial_." : ""}\n\n` : ""}## 📁 File Structure

\`\`\`
${slugify(skill.name)}/
├── SKILL.md              ← Core skill definition
├── TUTORIAL.md           ← Step-by-step tutorial
├── README.md             ← This file
└── standards/
    ├── metadata.yml      ← Structured metadata
    ├── examples/         ← Example files
    └── templates/        ← Reusable templates
\`\`\`

## 🔗 Related Skills

This skill was generated by AI based on: ${skill.generatedFrom.join(", ")}.

---
*Generated by [SkillsSense](https://skillssense.vercel.app) · Difficulty: ${skill.difficulty || "intermediate"} · Est. time: ${skill.estimatedTime || "1 hour"}*
`;
}

function generateExamples(
  skill: GeneratedSkill,
  ext: string
): { filename: string; content: string }[] {
  const tagStr = skill.tags.join(" ").toLowerCase();
  const name = skill.name.toLowerCase();

  const examples: { filename: string; content: string }[] = [];

  if (ext === ".py") {
    examples.push({
      filename: `example-01-basic${ext}`,
      content: `# Basic usage example for: ${skill.name}
# ${skill.description}

# TODO: Replace with actual example code based on the skill
def main():
    print("Hello from ${skill.name}!")
    # Your implementation here

if __name__ == "__main__":
    main()
`,
    });
    if (tagStr.includes("ml") || tagStr.includes("ai") || tagStr.includes("machine learning")) {
      examples.push({
        filename: `example-02-with-data${ext}`,
        content: `# Advanced usage with data for: ${skill.name}
# This example demonstrates real-world usage

# TODO: Replace with actual ML/AI example
import json

def load_data(path: str):
    with open(path) as f:
        return json.load(f)

# TODO: Add model training/prediction logic
def predict(data):
    return {"result": "placeholder"}
`,
      });
    }
  } else if (ext === ".js" || ext === ".ts") {
    examples.push({
      filename: `example-01-basic${ext}`,
      content: `// Basic usage example for: ${skill.name}
// ${skill.description}

// TODO: Replace with actual example code
async function main() {
  console.log("Hello from ${skill.name}!");
  // Your implementation here
}

main().catch(console.error);
`,
    });
    examples.push({
      filename: `example-02-with-config${ext}`,
      content: `// Configuration example for: ${skill.name}

const config = {
  name: "${skill.name}",
  version: "1.0.0",
  // TODO: Add your configuration options
};

module.exports = config;
`,
    });
  } else if (ext === ".sh") {
    examples.push({
      filename: `example-01-basic.sh`,
      content: `#!/bin/bash
# Basic usage example for: ${skill.name}
# ${skill.description}

set -e

echo "Hello from ${skill.name}!"

# TODO: Replace with actual shell script implementation
# Your commands here
`,
    });
  } else {
    // Generic example
    examples.push({
      filename: `example-01${ext}`,
      content: `// Example for: ${skill.name}
// ${skill.description}

// TODO: Replace with actual implementation
`,
    });
  }

  return examples;
}

function generateTemplates(
  skill: GeneratedSkill,
  ext: string,
  configExt: string
): { filename: string; content: string }[] {
  const templates: { filename: string; content: string }[] = [];

  if (ext === ".py") {
    templates.push({
      filename: `template-base${ext}`,
      content: `#!/usr/bin/env python3
"""
${skill.name} - Base Template
${skill.description}
"""

import argparse
import logging
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


class ${skill.name.replace(/[^a-zA-Z0-9]/g, "")}Runner:
    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}

    def run(self, input_data):
        """Main execution logic"""
        logger.info("Starting ${skill.name}...")
        # TODO: Implement your logic
        result = {"status": "success", "data": input_data}
        return result


def main():
    parser = argparse.ArgumentParser(description="${skill.name}")
    parser.add_argument("--input", "-i", help="Input data path")
    args = parser.parse_args()

    runner = ${skill.name.replace(/[^a-zA-Z0-9]/g, "")}Runner()
    result = runner.run(args.input)
    print(result)


if __name__ == "__main__":
    main()
`,
    });
    templates.push({
      filename: `config${configExt}`,
      content: `# Configuration for ${skill.name}
# TODO: Customize these settings for your environment

version: "1.0.0"
name: "${slugify(skill.name)}"

# Execution settings
settings:
  timeout: 300
  retries: 3

# TODO: Add your custom configuration
`,
    });
  } else if (ext === ".js") {
    templates.push({
      filename: `template-base${ext}`,
      content: `/**
 * ${skill.name} - Base Template
 * ${skill.description}
 */

// TODO: Implement your logic
async function create${skill.name.replace(/[^a-zA-Z0-9]/g, "")}(options = {}) {
  const defaults = {
    timeout: 30000,
    retries: 3,
  };

  const config = { ...defaults, ...options };

  console.log("Starting ${skill.name} with config:", config);
  // Your implementation here

  return { status: "success" };
}

module.exports = { create${skill.name.replace(/[^a-zA-Z0-9]/g, "")} };
`,
    });
    templates.push({
      filename: `config${configExt}`,
      content: JSON.stringify(
        {
          name: slugify(skill.name),
          version: "1.0.0",
          settings: {
            timeout: 30000,
            retries: 3,
          },
        },
        null,
        2
      ),
    });
  } else {
    templates.push({
      filename: `template-base${ext}`,
      content: `// ${skill.name} - Base Template
// ${skill.description}

// TODO: Replace with actual template
`,
    });
  }

  return templates;
}

/**
 * Package a generated skill into a ZIP buffer
 */
export async function packageSkill(skill: GeneratedSkill): Promise<PackagedSkill> {
  const slug = slugify(skill.name);
  const { codeExt, configExt } = getFileExtensions(skill.name, skill.tags);

  const zip = new JSZip();

  // 1. SKILL.md
  zip.file(
    "SKILL.md",
    `---\nname: ${skill.name}\ncategory: ${skill.category}\ndescription: ${skill.description}\ntags: [${skill.tags.join(", ")}]\nwhenToUse: ${skill.whenToUse}\nsource: generated\nurl: ""\ngeneratedFrom: [${skill.generatedFrom.map((s) => `"${s}"`).join(", ")}]\nprerequisites: [${(skill.prerequisites || []).map((s) => `"${s}"`).join(", ")}]\ndifficulty: ${skill.difficulty || "intermediate"}\nestimatedTime: ${skill.estimatedTime || "1 hour"}\n---\n\n# ${skill.name}\n\n${skill.description}\n\n## 🎯 When to Use\n\n${skill.whenToUse}\n\n${(skill.prerequisites || []).length > 0 ? `## 📋 Prerequisites\n\n${(skill.prerequisites || []).map((p) => `- ${p}`).join("\n")}\n\n` : ""}${skill.tutorial ? `## 📖 Tutorial\n\n${skill.tutorial}\n\n` : ""}## 📚 What You Will Learn\n\n${(skill.whatYouWillLearn || []).map((w) => `- ${w}`).join("\n")}\n\n## 🔗 Related Skills\n\nThis skill was generated by AI based on: ${skill.generatedFrom.join(", ")}.\n\n---\n*Generated by [SkillsSense](https://skillssense.vercel.app) · Difficulty: ${skill.difficulty || "intermediate"} · Est. time: ${skill.estimatedTime || "1 hour"}*\n`
  );

  // 2. TUTORIAL.md
  zip.file("TUTORIAL.md", skill.tutorial);

  // 3. README.md
  zip.file("README.md", generateReadme(skill));

  // 4. standards/
  const standardsDir = zip.folder("standards")!;

  // metadata.yml
  standardsDir.file(
    "metadata.yml",
    generateMetadataYaml({ ...skill, slug })
  );

  // examples/
  const examplesDir = standardsDir.folder("examples")!;
  for (const example of generateExamples(skill, codeExt)) {
    examplesDir.file(example.filename, example.content);
  }

  // templates/
  const templatesDir = standardsDir.folder("templates")!;
  for (const tmpl of generateTemplates(skill, codeExt, configExt)) {
    templatesDir.file(tmpl.filename, tmpl.content);
  }

  const buffer = await zip.generateAsync({ type: "nodebuffer" });

  return {
    zip: buffer,
    slug,
    files: [
      "SKILL.md",
      "TUTORIAL.md",
      "README.md",
      "standards/metadata.yml",
      ...generateExamples(skill, codeExt).map((e) => `standards/examples/${e.filename}`),
      ...generateTemplates(skill, codeExt, configExt).map((t) => `standards/templates/${t.filename}`),
    ],
  };
}
